TypeError: Cannot read property 'payload' of undefined
The oauth2.0 web traffic has an empty body, thus invalid data for services actionSDK, dialogflow, smarthome. This correction will  hand over only valid web traffic to the services actionSDK, dialogflow, smarthome